# Generated by Django 5.0.7 on 2024-08-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_registerassistant_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerassistant',
            name='date_updated',
        ),
    ]
