# Generated by Django 5.0.7 on 2024-08-15 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_registroactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroactivity',
            name='progress_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
