# Generated by Django 5.0.7 on 2024-08-23 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_registroactivity_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroactivity',
            name='users',
            field=models.ManyToManyField(related_name='register_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
